### ISSUE TITLE
[BUG] Error in shell after creating a codespace

### ISSUE THREAD

**Issue by MateusDadalto** [graycoreio/mage2docker#56]
# :bug: Bug report

## Current Behavior

After setting up mage2docker-dolphin for the first time an error message appear in the end of the process

```
Finished configuring codespace.
Microsoft.VisualStudio.VSOnline.Core.Exceptions.VmAgentException: Error adding user permissions. OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "usermod": executable file not found in $PATH: unknown
                                                                              at Microsoft.VisualStudio.VSOnline.Agent.Ssh.SshServerManager.<>c__DisplayClass28_0.<<ConfigureSshServerAsync>b__0>d.MoveNext() in D:\a\1\s\src\VSOnline\CLI\Ssh\SshServerManager.cs:line 234
                                                                                        --- End of stack trace from previous location where exception was thrown ---
                                                                                                                                                                       at Microsoft.VsSaaS.Diagnostics.Extensions.DiagnosticsLoggerExtensions.OperationScopeWithCustomExceptionControlFlowAsync(IDiagnosticsLogger logger, String name, Func`2 callback, Func`3 errCallback, LogLevel logLevel)
                            at Microsoft.VsSaaS.Diagnostics.Extensions.DiagnosticsLoggerExtensions.OperationScopeWithCustomExceptionControlFlowAsync(IDiagnosticsLogger logger, String name, Func`2 callback, Func`3 errCallback, LogLevel logLevel)
                                                                    at Microsoft.VisualStudio.VSOnline.Agent.Ssh.SshServerManager.StartSshServer(TraceSource trace, IDiagnosticsLogger logger, ICommandLine commandLine) in D:\a\1\s\src\VSOnline\CLI\Ssh\SshServerManager.cs:line 81
                                                                                                     at Microsoft.CloudEnvironments.CLI.UnifiedContainers.UnifiedContainerManager.<>c__DisplayClass104_0.<<MonitorAndExecuteEnvironmentConfiguration>b__1>d.MoveNext() in D:\a\1\s\src\VSOnline\CLI\UnifiedContainers\UnifiedContainerManager.cs:line 972
```

## Minimal reproduction of the problem with instructions

Start a new dolphin codespace, wait for the setup to finish

## Environment

<pre><code>
Mage2Docker version: 6.0.0
Magento version: 2.4

 
Others:

</code></pre>

**Comment by damienwebdev** [comment]
@MateusDadalto is this still replicable?

**Comment by MateusDadalto** [comment]
Could not reproduce this bug. It seems that github fixed whatever was causing this interaction
